#!/usr/bin/env bash

# Run the rime-install script to set up the frontend
# This will export the rime_frontend variable
source <(curl -fsSL https://jyutping.net/rime-install)

# Run the schema installation script
# This uses the rime_frontend variable from the previous script
source <(curl -fsSL https://jyutping.net/rime-cantonese-install-schema)
