#!/usr/bin/env bash

curl -fsSL https://git.io/rime-install | bash -s -- \
  cantonese \
  emoji-cantonese \
  CanCLID/rime-loengfan \
  lotem/rime-octagram-data \
  lotem/rime-octagram-data@hant \
  cantonese@install:default
