#!/usr/bin/env bash

echo ""
echo "Installing IME files..."
curl -fsSL https://git.io/rime-install | rime_frontend="$rime_frontend" bash -s -- \
  cantonese \
  emoji-cantonese \
  CanCLID/rime-loengfan \
  lotem/rime-octagram-data \
  lotem/rime-octagram-data@hant \
  custom:set:config=default,key=installed_from,value=rime-cantonese \
  custom:set:config=default,key=menu/page_size,value=8 \
  custom:clear_schema_list \
  custom:add:schema=jyut6ping3 \
  custom:add:schema=cangjie5 \
  custom:add:schema=stroke \
  custom:add:schema=luna_pinyin

echo ""
echo "Successfully installed IME files to $rime_frontend"
